name = "youth-survey"
pages_build_output_dir = "public"
compatibility_date = "2026-05-01"

[[d1_databases]]
binding = "DB"
database_name = "youth-surveydb"
database_id = "696b3c5c-88ac-4a2c-9537-630fd384ee75"
